# experiment setting
gpu_ids: [0] 
omp_num_threads: 16
save_dir: results
seed: 0

# training/inference setting
optimizer_name: adamw
lr: 0.01
weight_decay: 0.0
scheduler_name: cosine_lr
milestones: [99999]
gamma: 0.1
max_epoch: 400
eval_interval: 1
save_interval: 200

# model setting
model_name: gin_based_net
in_dim: 128
hidden_dim: 386
n_layers: 4
use_bias: False
nonlinearity: relu
dropout_p: 0.0
norm_type: bn
use_affine_bn: False
width_factor: 1
algo: global_ep
sparsity: 0.7
w_init_method: kaiming_uniform
s_init_method: kaiming_normal
m_init_method: epl
r_method: sparsity_distribution
p_ratio: 0.8
r_ratio: 0.0

# dataset setting
dataset_name: ogbn-arxiv
dataset_dir:  datasets
n_worker: 4
