# experiment setting
gpu_ids: [0, 1] 
omp_num_threads: 64
save_dir: simple_results
seed: 0
use_non_blocking: True

# training/inference setting
optimizer_name: sgd
lr: 0.1
momentum: 0.9
weight_decay: 0.0001
scheduler_name: cosine_lr
gamma: 0.1
batch_size_per_gpu: 128
# batch_size_val_per_gpu: 512
# batch_size_test_per_gpu: 512
max_epoch: 100
eval_interval: 1
save_interval: 50

# model setting
model_name: resnet50
nonlinearity: relu
use_affine_bn: False
algo: global_ep
sparsity: 0.7
scale_method: dynamic_scaled
w_init_method: signed_kaiming_constant
s_init_method: kaiming_normal

# dataset setting
dataset_name: imagenet
dataset_dir:  datasets
train_val_ratio: 0.8
n_worker: 8
use_simple_transform: True 